#!/usr/bin/php
<?php
    $rb_script = 'xappldr.rb';
    $class_file = 'xappldr.class';
    $jruby_complete = 'jruby-complete.jar';
    if (!file_exists($rb_script)) {
        echo 'Error: Script file "' . $rb_script . '" not found!' . PHP_EOL;
        return;
    }
    if (!file_exists($jruby_complete)) {
        echo 'Error: Jar file "' . $jruby_complete . '" not found!' . PHP_EOL;
        return;
    }
    //
    // Calculate the checksum of the jruby-complete
    //

    //
    // Set the version variable
    //
    $founds = 0;
    $ver = '';
    $csum = '';
    $lines = file($rb_script);
    foreach($lines as $idx => $line) {
        if ($line == ('# V ='. PHP_EOL)) {
            $dt = date('YmdHis');
            $git = trim(shell_exec('git rev-parse HEAD 2>/dev/null'));
            $ver = $dt . '-' . $git;
            // Replace the line
            $lines[$idx] = ('V = "' . $ver . '"' . PHP_EOL);
            $founds += 1;
        } else if ($line == ('# S ='. PHP_EOL)) {
            $csum = hash_file("sha256", $jruby_complete)
            // Replace the line
            $lines[$idx] = ('S = "' . $csum . '"' . PHP_EOL);
            $founds += 1;
        }
        if ($founds == 2) {
            break;
        }
    }
    if ($ver === '') {
        echo 'Error: Invalid script file "' . $rb_script . 
            '". Version placeholder not found!' . PHP_EOL;
        return;
    }
    if ($csum === '') {
        echo 'Error: Invalid script file "' . $rb_script . 
            '". Checksum placeholder not found!' . PHP_EOL;
        return;
    }
    //
    // Compile/produce the .class file
    //
    $tmp_script = '___' . $rb_script . '___';
    $tmp_class = '___' . $rb_script . '___.class';
    $srv_class = $ver . '.server.class';
    file_put_contents($tmp_script, $lines);
    $output  = [];
    $ret_code = 0;
    $compile_cmd = 'jrubyc ' . $tmp_script . ' 2>&1';
    exec($compile_cmd, $output, $ret_code);
    if ($ret_code !== 0) {
        echo 'Error: Failed to compile the script file "' . $rb_script . 
            '"!' . PHP_EOL;
        echo implode(PHP_EOL, $output);
        return;    
    }
    unlink($tmp_script);
    if (copy($tmp_class, $srv_class) != true) {
        echo 'Error: Failed to produce the server .class file!' . PHP_EOL;
        return;
    }
    if (rename($tmp_class, $class_file) !== true) {
        echo 'Error: Failed to produce the final .class file!' . PHP_EOL;
        return;
    }
    echo "Success: Compilation finished!" . PHP_EOL;
?>
